### PR TITLE
Adding Find Peak Element

### PR DESCRIPTION
**Pull request by ikunal-04**
This is related to #6 .

### CODE REVIEW

**Review by d-coder111 — APPROVED** [review]
Seems fine👍
Do star it if it helped u as a beginner😊

**Comment by ikunal-04** [comment]
Hi @d-coder111 my pr is not accepted in hacktoberfest! Could you please tell me the possible  reason for it?

**Comment by d-coder111** [comment]
> Hi @d-coder111 my pr is not accepted in hacktoberfest! Could you please tell me the possible reason for it?
> 
> image

Try refreshing the page..because from my end i have merged ur pr and this repo is hacktoberfest-accepted also

**Comment by d-coder111** [comment]
Hey @ikunal-04 do let me the status

**Comment by ikunal-04** [comment]
It went into the waiting status:

image

**Comment by d-coder111** [comment]
> It went into the waiting status:
> 
> image

Ok 👍

**Pull request merged**
